version: '3.9'

services:
  wagtail:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"